baseURL = "http://opendatakerala.org/"
languageCode = "en-us"
title = "Open Data Kerala"
theme = "geekblog"

# Required to get well formatted code blocks
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true
enableGitInfo = true

[markup]
  [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9

[taxonomies]
  author = "authors"
  tag = "tags"
  series = "series"

[mediaTypes]
  [mediaTypes."application/atom+xml"]
    suffixes = ["xml"]

[outputFormats]
  [outputFormats.Atom]
    # https://validator.w3.org/feed/docs/atom.html#whatIsAtom
    name = "Atom"
    mediaType = "application/atom+xml"
    # generated file = <baseName>.<mediaType."application/atom+xml".suffixes[0]> = atom.xml
    baseName = "atom"
    isPlainText = false
    rel = "alternate"
    isHTML = false
    noUgly = true
    permalinkable = false

[outputs]
  home = ["HTML", "ATOM"]
  page = ["HTML"]
  section = ["HTML"]
  taxonomy = ["HTML"]
  term = ["HTML", "ATOM"]

[params]
  subtitle = "Datasets related to Kerala & Malayalam"
  description = "A Network of Institutions and Individuals to Promotes OpenData in Kerala"
  keywords = []
  images = []
  blogButton = "Read Our Blog"
  blogUrl = "/post"
  logo = "https://opendatakerala.org/logo.png"
  sitename = "OpenDataKerala"

[[menu.main]]
  name = "About Us"
  url = "#about"
  weight = 1

[[menu.main]]
  name = "Projects"
  url = "#projects"
  weight = 2

[[menu.main]]
  name = "Events"
  url = "#events"
  weight = 3

[[menu.main]]
  name = "News"
  url = "#news"
  weight = 4

[[menu.main]]
  name = "Community"
  url = "#community"
  weight = 5

[[menu.main]]
  name = "Contact Us"
  url = "#contact"
  weight = 6

# Social links
[[params.social]]
  name = "Twitter"
  url = "https://twitter.com/opendatakerala"
  icon = "fab fa-twitter"

[[params.social]]
  name = "Facebook"
  url = "https://www.facebook.com/opendatakerala/"
  icon = "fab fa-facebook-f"

[[params.social]]
  name = "GitHub"
  url = "https://github.com/opendatakerala"
  icon = "fab fa-github"



  # (Optional, default static/brand.svg) Set the path to a logo for the Geekblog
  # relative to your 'static/' folder.
#   logo = "logo.png"

  # (Optional, default 6) Set how many table of contents levels to be showed on page.
  # Use false to hide ToC, note that 0 will default to 6 (https://gohugo.io/functions/default/)
  # You can also specify this parameter per page in front matter.
  geekblogToC = 3

  # (Optional, default none) Add a link to your Legal Notice page to the site footer.
  # It can be either a remote url or a local file path relative to your content directory.
  geekblogLegalNotice = "https://opendatakerala.org"

  # (Optional, default none) Add a link to your Privacy Policy page to the site footer.
  # It can be either a remote url or a local file path relative to your content directory.
  geekblogPrivacyPolicy = "/privacy"

  # (Optional, default true) Add an anchor link to headlines.
  geekblogAnchor = true

  # (Optional, default true) Copy anchor url to clipboard on click.
  geekblogAnchorCopy = true

  # (Optional, default none) Sites main author.
  geekblogAuthor = "open data observer"

  logo = "logo.png"

  # (Optional, default none) Adds a "Content licensed under <license>" line to the footer.
  # Could be used if you want to define a default license for your content.
  [params.geekblogContentLicense]
    name = "CC BY-SA 4.0"
    link = "https://creativecommons.org/licenses/by-sa/4.0/"

